"""任务三服务常量定义"""

# ========== 问题分类与路由关键词 ==========

COMPANY_ALIAS_MAP = {
    "华润三九": ["三九", "999"],
}

KNOWLEDGE_ONLY_KEYWORDS = [
    "医保",
    "医保目录",
    "国家医保",
    "商保",
    "集采",
    "谈判",
    "政策",
    "目录",
    "新增",
    "产品有哪些",
    "名单",
    "北向资金",
    "外资",
    "撤退",
    "市场观点",
    "行业风向",
    "行业事件",
    "原因",
    "为什么",
    "为何",
    "导致",
    "因素",
    "影响",
    "驱动",
    "分析原因",
    "涨跌原因",
    "变化原因",
    "增长原因",
    "下降原因",
    "研报",
    "研究报告",
    "券商报告",
    "结合研报",
    "分析",
    "风险",
    "优势",
    "质量",
    "评估",
    "判断",
]

INDUSTRY_KNOWLEDGE_KEYWORDS = [
    "医保",
    "商保",
    "集采",
    "谈判",
    "政策",
    "目录",
    "新增",
    "北向资金",
    "外资",
    "行业",
]

FINANCIAL_DATA_KEYWORDS = [
    "货币资金",
    "总资产",
    "资产负债表",
    "现金流量",
    "现金流",
    "利润表",
    "营业收入",
    "净利润",
    "负债",
    "比率",
    "毛利率",
    "净利率",
    "ROE",
    "EPS",
    "占比",
    "比例",
    "同比增长",
    "环比",
    "增速",
    "金额",
    "万元",
    "亿元",
    "应收账款",
    "存货",
    "在建工程",
    "短期借款",
    "总负债",
    "经营性现金流",
    "投资性现金流",
    "融资性现金流",
    "每股收益",
    "净资产收益率",
    "销售毛利率",
    "销售净利率",
    "扣非净利润",
    "资产负债率",
    "总资产同比",
    "净现金流",
    "财务",
    "主营业务收入",
    "营收",
    "盈利",
    "亏损",
    "利润总额",
    "经营性现金流量净额",
    "资产减值",
    "信用减值",
    "折旧",
    "摊销",
    "营业总收入",
    "增长率",
    "费用率",
]

ATTRIBUTION_KEYWORDS = [
    "原因",
    "为什么",
    "为何",
    "导致",
    "解释",
    "归因",
    "驱动因素",
    "影响因素",
    "背离",
    "背离现象",
    "差异原因",
    "变动原因",
    "下降原因",
    "增长原因",
    "变化原因",
    "分析原因",
    "涨跌原因",
    "分析",
    "风险",
    "优势",
    "质量",
    "评估",
    "判断",
]

MULTI_INTENT_ACTION_KEYWORDS = [
    "查询",
    "统计",
    "计算",
    "找出",
    "列出",
    "筛选",
    "提取",
    "对比",
    "比较",
    "分析",
    "验证",
    "说明",
    "评价",
    "评估",
    "给出",
]


# ========== SQL执行与校验 ==========

TASK3_TABLE_SCHEMA: dict[str, dict[str, str]] = {
    "income_sheet": {
        "report_id": "财报主表ID",
        "stock_code": "股票代码",
        "stock_abbr": "股票简称",
        "report_year": "报告年份",
        "report_period": "报告期：Q1/HY/Q3/FY",
        "report_type": "报告类型：REPORT/SUMMARY",
        "net_profit": "净利润(万元)",
        "net_profit_yoy_growth": "净利润同比(%)",
        "other_income": "其他收益(万元)",
        "total_operating_revenue": "营业总收入(万元)",
        "operating_revenue_yoy_growth": "营业总收入同比(%)",
        "operating_expense_cost_of_sales": "营业总支出-营业支出(万元)",
        "operating_expense_selling_expenses": "营业总支出-销售费用(万元)",
        "operating_expense_administrative_expenses": "营业总支出-管理费用(万元)",
        "operating_expense_financial_expenses": "营业总支出-财务费用(万元)",
        "operating_expense_rnd_expenses": "营业总支出-研发费用(万元)",
        "operating_expense_taxes_and_surcharges": "营业总支出-税金及附加(万元)",
        "total_operating_expenses": "营业总支出(万元)",
        "operating_profit": "营业利润(万元)",
        "total_profit": "利润总额(万元)",
        "asset_impairment_loss": "资产减值损失(万元)",
        "credit_impairment_loss": "信用减值损失(万元)",
    },
    "balance_sheet": {
        "report_id": "财报主表ID",
        "stock_code": "股票代码",
        "stock_abbr": "股票简称",
        "report_year": "报告年份",
        "report_period": "报告期：Q1/HY/Q3/FY",
        "report_type": "报告类型：REPORT/SUMMARY",
        "asset_cash_and_cash_equivalents": "资产-货币资金(万元)",
        "asset_accounts_receivable": "资产-应收账款(万元)",
        "asset_inventory": "资产-存货(万元)",
        "asset_trading_financial_assets": "资产-交易性金融资产(万元)",
        "asset_construction_in_progress": "资产-在建工程(万元)",
        "asset_total_assets": "资产-总资产(万元)",
        "asset_total_assets_yoy_growth": "资产-总资产同比(%)",
        "liability_accounts_payable": "负债-应付账款(万元)",
        "liability_advance_from_customers": "负债-预收账款(万元)",
        "liability_total_liabilities": "负债-总负债(万元)",
        "liability_total_liabilities_yoy_growth": "负债-总负债同比(%)",
        "liability_contract_liabilities": "负债-合同负债(万元)",
        "liability_short_term_loans": "负债-短期借款(万元)",
        "asset_liability_ratio": "资产负债率(%)",
        "equity_unappropriated_profit": "股东权益-未分配利润(万元)",
        "equity_total_equity": "股东权益合计(万元)",
    },
    "cash_flow_sheet": {
        "report_id": "财报主表ID",
        "stock_code": "股票代码",
        "stock_abbr": "股票简称",
        "report_year": "报告年份",
        "report_period": "报告期：Q1/HY/Q3/FY",
        "report_type": "报告类型：REPORT/SUMMARY",
        "net_cash_flow": "净现金流(元)",
        "net_cash_flow_yoy_growth": "净现金流-同比增长(%)",
        "operating_cf_net_amount": "经营性现金流-现金流量净额(万元)",
        "operating_cf_ratio_of_net_cf": "经营性现金流-净现金流占比(%)",
        "operating_cf_cash_from_sales": "经营性现金流-销售商品收到的现金(万元)",
        "investing_cf_net_amount": "投资性现金流-现金流量净额(万元)",
        "investing_cf_ratio_of_net_cf": "投资性现金流-净现金流占比(%)",
        "investing_cf_cash_for_investments": "投资性现金流-投资支付的现金(万元)",
        "investing_cf_cash_from_investment_recovery": "投资性现金流-收回投资收到的现金(万元)",
        "financing_cf_cash_from_borrowing": "融资性现金流-取得借款收到的现金(万元)",
        "financing_cf_cash_for_debt_repayment": "融资性现金流-偿还债务支付的现金(万元)",
        "financing_cf_net_amount": "融资性现金流-现金流量净额(万元)",
        "financing_cf_ratio_of_net_cf": "融资性现金流-净现金流占比(%)",
    },
    "core_performance_indicators_sheet": {
        "report_id": "财报主表ID",
        "stock_code": "股票代码",
        "stock_abbr": "股票简称",
        "report_year": "报告年份",
        "report_period": "报告期：Q1/HY/Q3/FY",
        "report_type": "报告类型：REPORT/SUMMARY",
        "eps": "每股收益(元)",
        "total_operating_revenue": "营业总收入(万元)",
        "operating_revenue_yoy_growth": "营业总收入-同比增长(%)",
        "operating_revenue_qoq_growth": "营业总收入-季度环比增长(%)",
        "net_profit_10k_yuan": "净利润(万元)",
        "net_profit_yoy_growth": "净利润-同比增长(%)",
        "net_profit_qoq_growth": "净利润-季度环比增长(%)",
        "net_asset_per_share": "每股净资产(元)",
        "roe": "净资产收益率(%)",
        "operating_cf_per_share": "每股经营现金流量(元)",
        "net_profit_excl_non_recurring": "扣非净利润(万元)",
        "net_profit_excl_non_recurring_yoy": "扣非净利润同比增长(%)",
        "gross_profit_margin": "销售毛利率(%)",
        "net_profit_margin": "销售净利率(%)",
        "roe_weighted_excl_non_recurring": "加权平均净资产收益率(扣非)(%)",
    },
    "company_basic_info": {
        "stock_code": "股票代码",
        "stock_abbr": "股票简称",
        "company_name": "公司名称",
        "english_name": "英文名称",
        "csrc_industry": "所属证监会行业",
        "listed_exchange": "上市交易所原始文本",
        "exchange": "标准化交易所代码：SH/SZ/BJ",
        "security_category": "证券类别",
        "registered_region": "注册区域",
        "registered_capital_raw": "注册资本原始文本",
        "registered_capital_yuan": "注册资本标准化数值(元)",
        "employee_count": "雇员人数",
        "management_count": "管理人员人数",
        "source_row_no": "附件1原始序号",
        "source_file_name": "附件1源文件名",
        "created_at": "创建时间",
        "updated_at": "更新时间",
    },
}

ALLOWED_TABLES = list(TASK3_TABLE_SCHEMA.keys())

FORBIDDEN_KEYWORDS = [
    "DROP",
    "DELETE",
    "UPDATE",
    "INSERT",
    "ALTER",
    "CREATE",
    "TRUNCATE",
    "GRANT",
    "REVOKE",
]
SQL_RESERVED_IDENTIFIERS = {
    "ALL",
    "AND",
    "AS",
    "ASC",
    "BETWEEN",
    "BY",
    "CASE",
    "CROSS",
    "DESC",
    "DISTINCT",
    "ELSE",
    "END",
    "EXISTS",
    "FALSE",
    "FROM",
    "FULL",
    "GROUP",
    "HAVING",
    "IN",
    "INNER",
    "IS",
    "JOIN",
    "LEFT",
    "LIKE",
    "LIMIT",
    "NOT",
    "NULL",
    "OFFSET",
    "ON",
    "OR",
    "ORDER",
    "OUTER",
    "RIGHT",
    "ROWS",
    "SELECT",
    "THEN",
    "TRUE",
    "WHEN",
    "WHERE",
    "WITH",
    "UNION",
}
SQL_FUNCTIONS = {
    "ABS",
    "AVG",
    "CAST",
    "COALESCE",
    "CONCAT",
    "COUNT",
    "IFNULL",
    "MAX",
    "MIN",
    "NULLIF",
    "ROUND",
    "SUM",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "NOW",
    "CURDATE",
    "CURTIME",
    "DATE",
    "YEAR",
    "MONTH",
    "DAY",
    "QUARTER",
    "WEEK",
    "STR_TO_DATE",
    "DATE_FORMAT",
}

# ========== 答案校验 ==========

ATTRIBUTION_KEYWORDS = [
    "原因",
    "为什么",
    "为何",
    "导致",
    "解释",
    "归因",
    "驱动因素",
    "影响因素",
    "背离",
    "差异原因",
    "变动原因",
    "分析原因",
]

FINANCIAL_DATA_KEYWORDS = [
    "资产负债表",
    "现金流",
    "现金流量",
    "利润表",
    "营业收入",
    "营业总收入",
    "应收账款",
    "占比",
    "比例",
    "财务",
    "总资产",
    "总负债",
    "净利润",
    "营收",
]

CAUSE_KEYWORDS = [
    "原因",
    "是因为",
    "由于",
    "主要因为",
    "影响因素",
    "导致",
    "造成",
    "为何",
    "为什么",
]

MISSING_FINANCIAL_DATA_PATTERNS = [
    r"无财务数据",
    r"缺少[^。；\n]{0,30}财务数据",
    r"没有[^。；\n]{0,30}财务数据",
    r"无[^。；\n]{0,30}资产负债表",
    r"缺少[^。；\n]{0,30}资产负债表",
    r"无[^。；\n]{0,30}应收账款[^。；\n]{0,20}收入数据",
    r"缺少[^。；\n]{0,30}应收账款[^。；\n]{0,20}收入数据",
]

INCOMPLETE_ANSWER_PATTERNS = [
    r"无法计算",
    r"无法完成",
    r"无法验证",
    r"无法执行",
    r"无法直接回答",
    r"暂时无法",
    r"未检索到",
    r"未获取到",
    r"无数据",
    r"不完整",
    r"部分失败",
    r"数据仅覆盖",
    r"缺少20\d{2}",
    r"建议执行补充查询",
    r"请确认是否已完成",
]

REFERENCE_REQUIRED_KEYWORDS = [
    "研报",
    "研究报告",
    "券商报告",
    "结合研报",
    "风险",
    "风险预警",
    "核心竞争力",
    "评价",
    "规划",
    "项目说明",
    "可靠性",
]
